CREATE TABLE [dbo].[crops] (
    [crop_id]               INT            IDENTITY (1, 1) NOT NULL,
    [genus]                 VARCHAR (50)   NOT NULL,
    [species]               VARCHAR (50)   NOT NULL,
    [crop]                  VARCHAR (50)   NULL,
    [crop_kind]             VARCHAR (50)   NULL,
    [crop_renew_years]      INT            NULL,
    [app_due]               INT            NULL,
    [user_entered]          VARCHAR (9)    NULL,
    [date_entered]          DATETIME       NULL,
    [user_modified]         VARCHAR (9)    NULL,
    [date_modified]         DATETIME       NULL,
    [annual]                CHAR (1)       NULL,
    [qb_class]              VARCHAR (50)   NULL,
    [qb_invitem]            VARCHAR (50)   NULL,
    [report_group]          VARCHAR (50)   NULL,
    [certified_crop]        BIT            CONSTRAINT [DF_crops_certified_crop] DEFAULT ((1)) NOT NULL,
    [isolation_crop]        BIT            CONSTRAINT [DF_crops_isolation_crop] DEFAULT ((0)) NOT NULL,
    [heritage]              BIT            NOT NULL,
    [pre_variety_germplasm] BIT            CONSTRAINT [DF_crops_pre_variety_germplasm] DEFAULT ((0)) NOT NULL,
    [isolation_foundation]  DECIMAL (5, 1) NULL,
    [isolation_registered]  DECIMAL (5, 1) NULL,
    [isolation_certified]   DECIMAL (5, 1) NULL,
    [isolation_hybrid]      DECIMAL (6, 2) NULL,
    [isolation_parent_a]    DECIMAL (6, 2) NULL,
    [isolation_parent_b]    DECIMAL (6, 2) NULL,
    [isolation_parent_r]    DECIMAL (6, 2) NULL,
    [fov4_map]              BIT            CONSTRAINT [DF_crops_fov4_map] DEFAULT ((0)) NOT NULL,
    [idaho_crop_name]       VARCHAR (50)   NULL,
    [idaho_field_type]      VARCHAR (50)   NULL,
    [idaho_vegetable]       BIT            CONSTRAINT [DF_crops_idaho_vegetable] DEFAULT ((0)) NOT NULL,
    [lactracker]            BIT            CONSTRAINT [DF_crops_lactracker] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Crops] PRIMARY KEY CLUSTERED ([crop_id] ASC)
);



