CREATE TABLE [dbo].[crops] (
    [crop_id]                INT             IDENTITY (1, 1) NOT NULL,
    [genus]                  VARCHAR (50)    NOT NULL,
    [species]                VARCHAR (50)    NOT NULL,
    [crop]                   VARCHAR (50)    NULL,
    [crop_kind]              VARCHAR (50)    NULL,
    [crop_renew_years]       SMALLINT        NULL,
    [app_due]                SMALLINT        NULL,
    [user_entered]           VARCHAR (9)     NULL,
    [date_entered]           DATETIME        NULL,
    [user_modified]          VARCHAR (9)     NULL,
    [date_modified]          DATETIME        NULL,
    [annual]                 CHAR (1)        NULL,
    [qb_class]               VARCHAR (50)    NULL,
    [qb_invitem]             VARCHAR (50)    NULL,
    [report_group]           VARCHAR (50)    NULL,
    [certified_crop]         BIT             CONSTRAINT [DF_crops_certified_crop] DEFAULT ((0)) NOT NULL,
    [heritage]               BIT             CONSTRAINT [DF_crops_heritage] DEFAULT ((0)) NOT NULL,
    [pre_variety_germplasm]  BIT             CONSTRAINT [DF_crops_pre_variety_germplasm] DEFAULT ((0)) NOT NULL,
    [fov4_map]               BIT             CONSTRAINT [DF_crops_fov4_map] DEFAULT ((0)) NOT NULL,
    [isolation_crop]         BIT             CONSTRAINT [DF_crops_isolation_crop] DEFAULT ((0)) NOT NULL,
    [idaho_vegetable]        BIT             CONSTRAINT [DF_crops_idaho_vegetable] DEFAULT ((0)) NOT NULL,
    [idaho_field_type]       VARCHAR (50)    NULL,
    [idaho_crop_name]        VARCHAR (50)    NULL,
    [isolation_foundation]   NUMERIC (10, 1) NULL,
    [isolation_registered]   NUMERIC (10, 1) NULL,
    [isolation_certified]    NUMERIC (10, 1) NULL,
    [isolation_hybrid]       NUMERIC (10, 1) NULL,
    [isolation_parent_a]     NUMERIC (10, 1) NULL,
    [isolation_parent_b]     NUMERIC (10, 1) NULL,
    [isolation_parent_r]     NUMERIC (10, 1) NULL,
    [audit_cond_sample_size] SMALLINT        NULL,
    [audit_lab_sample_size]  SMALLINT        NULL,
    CONSTRAINT [PK_Crops] PRIMARY KEY CLUSTERED ([crop_id] ASC)
);

