CREATE TABLE [dbo].[idaho_beta_isolation] (
    [field_type]                         VARCHAR (50)    NOT NULL,
    [sugar_beets_hybrid]                 NUMERIC (10, 1) NOT NULL,
    [sugar_beets_op]                     NUMERIC (10, 1) NOT NULL,
    [sugar_beets_gmo]                    NUMERIC (10, 1) NOT NULL,
    [sugar_beets_stock]                  NUMERIC (10, 1) NOT NULL,
    [sugar_beets_research_station]       NUMERIC (10, 1) NOT NULL,
    [table_beets_hybrid]                 NUMERIC (10, 1) NOT NULL,
    [table_beets_op]                     NUMERIC (10, 1) NOT NULL,
    [table_beets_gmo]                    NUMERIC (10, 1) NOT NULL,
    [table_beets_stock]                  NUMERIC (10, 1) NOT NULL,
    [table_beets_research_station]       NUMERIC (10, 1) NOT NULL,
    [fodder_beets_hybrid]                NUMERIC (10, 1) NOT NULL,
    [fodder_beets_op]                    NUMERIC (10, 1) NOT NULL,
    [fodder_beets_gmo]                   NUMERIC (10, 1) NOT NULL,
    [fodder_beets_stock]                 NUMERIC (10, 1) NOT NULL,
    [fodder_beets_research_station]      NUMERIC (10, 1) NOT NULL,
    [swiss_chard_red_hybrid]             NUMERIC (10, 1) NOT NULL,
    [Swiss_chard_red_op]                 NUMERIC (10, 1) NOT NULL,
    [swiss_chard_red_gmo]                NUMERIC (10, 1) NOT NULL,
    [swiss_chard_red_stock]              NUMERIC (10, 1) NOT NULL,
    [swiss_chard_red_research_station]   NUMERIC (10, 1) NOT NULL,
    [swiss_chard_green_hybrid]           NUMERIC (10, 1) NOT NULL,
    [Swiss_chard_green_op]               NUMERIC (10, 1) NOT NULL,
    [swiss_chard_green_gmo]              NUMERIC (10, 1) NOT NULL,
    [swiss_chard_green_stock]            NUMERIC (10, 1) NOT NULL,
    [swiss_chard_green_research_station] NUMERIC (10, 1) NOT NULL
);

