CREATE TABLE [dbo].[organization_deleted] (
    [org_id]                     INT            NOT NULL,
    [org_name]                   NVARCHAR (250) NOT NULL,
    [org_type]                   VARCHAR (50)   NULL,
    [address_id]                 INT            NULL,
    [main_phone]                 VARCHAR (15)   NULL,
    [main_email]                 VARCHAR (100)  NULL,
    [main_fax]                   VARCHAR (15)   NULL,
    [website]                    VARCHAR (100)  NULL,
    [conditioner]                BIT            NOT NULL,
    [conditioner_status]         VARCHAR (2)    NOT NULL,
    [conditioner_update]         DATETIME       NULL,
    [allow_pretag]               BIT            NOT NULL,
    [print_series_tags]          BIT            NOT NULL,
    [date_pretag_approved]       DATETIME       NULL,
    [foundation_seed_contractor] BIT            NOT NULL,
    [foundation_seed_grower]     BIT            NOT NULL,
    [diagnostic_lab]             BIT            NOT NULL,
    [diagnostic_lab_init_year]   DATETIME       NULL,
    [germination_lab]            BIT            NOT NULL,
    [aosca_member]               BIT            NOT NULL,
    [ag_comm_off]                BIT            NOT NULL,
    [county_id]                  INT            NULL,
    [grower]                     BIT            NOT NULL,
    [oecd_shipper]               BIT            NOT NULL,
    [district]                   VARCHAR (5)    NULL,
    [ccia_member]                BIT            NOT NULL,
    [member_year]                SMALLINT       NULL,
    [member_type]                VARCHAR (50)   NULL,
    [last_member_agreement]      DATETIME       NULL,
    [member_since]               DATETIME       NULL,
    [member_rep_id]              INT            NULL,
    [agreement_year]             SMALLINT       NULL,
    [active]                     BIT            NOT NULL,
    [contact_type]               VARCHAR (50)   NULL,
    [user_modified]              VARCHAR (50)   NULL,
    [date_modified]              DATETIME       NULL,
    [keywords]                   VARCHAR (1000) NULL,
    [notes]                      VARCHAR (500)  NULL,
    [password]                   VARCHAR (50)   NULL,
    [app_agree_accept]           SMALLINT       NULL,
    [allow_alfalfa_gmo_pinning]  BIT            NOT NULL
);

