CREATE TABLE [dbo].[seedlab_purity] (
    [lab_id]                       INT            NOT NULL,
    [weight_working_sample]        FLOAT (53)     NULL,
    [other_crop_grams]             FLOAT (53)     CONSTRAINT [DF_seedlab_purity_other_crop_grams] DEFAULT ((0)) NULL,
    [other_crop_count]             SMALLINT       NULL,
    [other_variety_grams]          FLOAT (53)     NULL,
    [other_variety_count]          SMALLINT       NULL,
    [inert_grams]                  FLOAT (53)     CONSTRAINT [DF_seedlab_purity_inert_grams] DEFAULT ((0)) NULL,
    [inert_description]            VARCHAR (5000) NULL,
    [inert_soil]                   BIT            CONSTRAINT [DF_seedlab_purity_inert_soil] DEFAULT ((0)) NOT NULL,
    [inert_dirt]                   BIT            CONSTRAINT [DF_seedlab_purity_inert_dirt] DEFAULT ((0)) NOT NULL,
    [inert_seed_fragments]         BIT            CONSTRAINT [DF_seedlab_purity_inert_seed_fragments] DEFAULT ((0)) NOT NULL,
    [inert_chaff]                  BIT            CONSTRAINT [DF_seedlab_purity_inert_chaff] DEFAULT ((0)) NOT NULL,
    [inert_plant_fragments]        BIT            CONSTRAINT [DF_seedlab_purity_inert_plant_fragments] DEFAULT ((0)) NOT NULL,
    [inert_stems]                  BIT            CONSTRAINT [DF_seedlab_purity_inert_stems] DEFAULT ((0)) NOT NULL,
    [inert_treatment_colorant]     BIT            CONSTRAINT [DF_seedlab_purity_inert_treatment_colorant] DEFAULT ((0)) NOT NULL,
    [weed_seed_grams]              FLOAT (53)     CONSTRAINT [DF_seedlab_purity_weed_seed_grams] DEFAULT ((0)) NULL,
    [weed_seed_count]              SMALLINT       NULL,
    [pure_seed_grams]              FLOAT (53)     CONSTRAINT [DF_seedlab_purity_pure_seed_grams] DEFAULT ((0)) NULL,
    [report_purity]                DECIMAL (5, 2) NULL,
    [report_other_crop]            DECIMAL (5, 2) NULL,
    [report_inert]                 DECIMAL (5, 2) NULL,
    [report_weed]                  DECIMAL (5, 2) NULL,
    [report_other_variety]         DECIMAL (5, 2) NULL,
    [bushel_weight]                FLOAT (53)     NULL,
    [date_completed]               DATE           NULL,
    [completed_by]                 VARCHAR (50)   NULL,
    [comments]                     VARCHAR (5000) NULL,
    [insufficient_size_purity]     BIT            CONSTRAINT [DF_seedlab_purity_insufficient_size_purity] DEFAULT ((0)) NOT NULL,
    [calc_purity]                  DECIMAL (5, 2) NULL,
    [calc_other_crop]              DECIMAL (5, 2) NULL,
    [calc_inert]                   DECIMAL (5, 2) NULL,
    [calc_weed]                    DECIMAL (5, 2) NULL,
    [foreign_material_grams]       FLOAT (53)     NULL,
    [splits_cracks_grams]          FLOAT (53)     NULL,
    [badly_discolored_grams]       FLOAT (53)     NULL,
    [chewing_insect_damage_grams]  FLOAT (53)     NULL,
    [calc_foreign_material]        DECIMAL (5, 2) NULL,
    [calc_splits_and_cracks]       DECIMAL (5, 2) NULL,
    [calc_badly_discolored]        DECIMAL (5, 2) NULL,
    [calc_chewing_insect_damage]   DECIMAL (5, 2) NULL,
    [report_foreign_material]      DECIMAL (5, 2) NULL,
    [report_splits_cracks]         DECIMAL (5, 2) NULL,
    [report_badly_discolored]      DECIMAL (5, 2) NULL,
    [report_chewing_insect_damage] DECIMAL (5, 2) NULL,
    CONSTRAINT [PK_seedlab_purity] PRIMARY KEY NONCLUSTERED ([lab_id] ASC)
);

